name: website

on:
  push:
    branches:
      - main

jobs:

  build:
    name: build and deploy website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install mdbook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.3.5'
    - name: build book
      run: |
        cd docs && mdbook build
    - name: Deploy to firebase
      uses: w9jds/firebase-action@v1.1.0
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
